import 'package:flutter/material.dart';

class MakeAppTextTheme extends TextTheme {
  MakeAppTextTheme()
      : super(
          headline1: TextStyle(
            fontFamily: "NotoSansJP",
            fontStyle: FontStyle.normal,
            fontSize: 30,
            fontWeight: FontWeight.bold,
            letterSpacing: 0.12,
            height: 1.5,
            color: Color(0xffE9EAEC),
          ),
          headline2: TextStyle(
            fontFamily: "NotoSansJP",
            fontWeight: FontWeight.normal,
            fontStyle: FontStyle.normal,
            fontSize: 22.0,
            letterSpacing: 0.12,
            height: 1.5,
          ),
          headline3: TextStyle(
            fontFamily: "NotoSansJP",
            fontWeight: FontWeight.normal,
            fontStyle: FontStyle.normal,
            fontSize: 20.0,
            letterSpacing: 0.12,
            height: 1.5,
          ),
          headline4: TextStyle(
            fontFamily: "NotoSansJP",
            fontWeight: FontWeight.normal,
            fontStyle: FontStyle.normal,
            fontSize: 18.0,
            letterSpacing: 0.12,
            height: 1.5,
          ),
          headline5: TextStyle(
            fontFamily: "NotoSansJP",
            fontWeight: FontWeight.normal,
            fontStyle: FontStyle.normal,
            fontSize: 16.0,
            letterSpacing: 0.12,
            height: 1.5,
          ),
          headline6: TextStyle(
            fontFamily: "NotoSansJP",
            fontWeight: FontWeight.normal,
            fontStyle: FontStyle.normal,
            fontSize: 14.0,
            letterSpacing: 0.12,
            height: 1.5,
          ),
          subtitle1: TextStyle(
            fontFamily: "NotoSansJP",
            fontWeight: FontWeight.w700,
            fontStyle: FontStyle.normal,
            fontSize: 20.0,
            letterSpacing: 0.09,
            height: 1.5,
            color: Color(0xffFAD02C),
          ),
          subtitle2: TextStyle(
            fontFamily: "NotoSansJP",
            fontWeight: FontWeight.normal,
            fontStyle: FontStyle.normal,
            fontSize: 18.0,
            letterSpacing: 0.09,
            height: 1.5,
            color: Color(0xff90ADC6),
          ),
          bodyText1: TextStyle(
            fontFamily: "NotoSansJP",
            fontWeight: FontWeight.normal,
            fontStyle: FontStyle.normal,
            fontSize: 18.0,
            letterSpacing: 0.0,
            height: 1.5,
          ),
          bodyText2: TextStyle(
            fontFamily: "NotoSansJP",
            fontSize: 16.0,
            fontWeight: FontWeight.normal,
            fontStyle: FontStyle.normal,
            letterSpacing: 0.0,
            height: 1.5,
          ),
          button: TextStyle(
            fontFamily: "NotoSansJP",
            fontSize: 16.0,
            fontWeight: FontWeight.w700,
            fontStyle: FontStyle.normal,
            letterSpacing: 0.0,
            height: 1.5,
            color: Colors.black,
          ),
          caption: TextStyle(
            fontFamily: "NotoSansJP",
            fontSize: 18.0,
            fontWeight: FontWeight.normal,
            fontStyle: FontStyle.normal,
            letterSpacing: 0.0,
            height: 1.5,
            color: Color(0xffE9EAEC),
          ),
          overline: TextStyle(
            fontFamily: "NotoSansJP",
            fontSize: 11.0,
            fontWeight: FontWeight.normal,
            fontStyle: FontStyle.normal,
            letterSpacing: 0.0,
            height: 1.45,
          ),
        );
}
